Removed nmap_scanner func. Moved commands to drop temp scan tables to their own function. Other minor tweaks.

diff --git a/wakelan_v2 b/wakelan_v2
--- a/wakelan_v2
+++ b/wakelan_v2
@@ -1,5 +1,4 @@
 #!/bin/bash
-
 #  wakelan- Wakes up computers on LAN.
 #
 #  Copyright 2012 Lemar Carthens <lemar.carthens1@gmail.com>
@@ -18,9 +17,8 @@
 #  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 #  MA 02110-1301, USA.
 #  
-
 #  Version 2 - SQLite Support
-#       
+#
 #  Resources from: 
 #  http://www.sqlite.org/
 #  http://quickies.andreaolivato.net/post/133473114/using-sqlite3-in-bash
@@ -37,7 +35,7 @@ ARPSCAN="/usr/bin/arp-scan"
 NBTSCAN="/usr/bin/nbtscan"
 WAKEONLAN="/usr/bin/wakeonlan"
 
-# Declare the program_info and sql_func as associative arrays
+# Declare all of the associative arrays at the top of the script. 
 # This prevents a 'bad array subscript' error.
 declare -A prog_info
 declare -A sql_func
@@ -47,9 +45,6 @@ declare -A scan_opt
 trap "signal_exit TERM" TERM HUP
 trap "signal_exit INT"  INT
 
-# Associative arrays allow the string to be called easily and descriptively.
-# ex. program_info VERSION
- 
 program_info()
 {
     prog_info[PROGNAME]=$(basename $0)
@@ -63,24 +58,18 @@ load_sql()
 {   
     # SQL Program
     sql_func[DB_TYPE]="sqlite3" 
-    
     # SQL Database Name
     sql_func[DB_NAME]="wakelan.db"
-    
     # SQL Table Names
     sql_func[TABLE_NAME]="client"
     sql_func[TEMP_TABLE_NAME]="temp_${sql_func[TABLE_NAME]}"
     sql_func[ARPSCAN_TEMP_TABLE_NAME]="arpscan_temp_${sql_func[TABLE_NAME]}"
     sql_func[NBTSCAN_TEMP_TABLE_NAME]="nbtscan_temp_${sql_func[TABLE_NAME]}"
- 
-    
     # Table Creation SQL
     sql_func[CREATE_MAIN_TABLE]="CREATE TABLE ${sql_func[TABLE_NAME]} (id INTEGER PRIMARY KEY,IpAddress TEXT,Hostname TEXT COLLATE NOCASE, MacAddress TEXT COLLATE NOCASE,UNIQUE(id,MacAddress) ON CONFLICT REPLACE);"
     sql_func[CREATE_TEMP_TABLE]="CREATE TABLE ${sql_func[TEMP_TABLE_NAME]} (IpAddress TEXT,Hostname TEXT COLLATE NOCASE, MacAddress TEXT COLLATE NOCASE);"
     sql_func[CREATE_ARPSCAN_TEMP_TABLE]="CREATE TABLE ${sql_func[ARPSCAN_TEMP_TABLE_NAME]} (IpAddress TEXT,Hostname TEXT COLLATE NOCASE, MacAddress TEXT COLLATE NOCASE);"
-    sql_func[CREATE_NBTSCAN_TEMP_TABLE]="CREATE TABLE ${sql_func[NBTSCAN_TEMP_TABLE_NAME]} (IpAddress TEXT,Hostname TEXT COLLATE NOCASE, MacAddress TEXT COLLATE NOCASE);"    
-
-    
+    sql_func[CREATE_NBTSCAN_TEMP_TABLE]="CREATE TABLE ${sql_func[NBTSCAN_TEMP_TABLE_NAME]} (IpAddress TEXT,Hostname TEXT COLLATE NOCASE, MacAddress TEXT COLLATE NOCASE);"
     # SQL for getting rid of duplicate values. 
     # It Deletes every Value from the arpscan_temp_client 
     # table where the MAC address corresponds to the value 
@@ -88,23 +77,17 @@ load_sql()
     # because nbtscan will give you a hostname, while
     # arpscan dosent.
     sql_func[DROP_DUPLICATES]="DELETE FROM ${sql_func[ARPSCAN_TEMP_TABLE_NAME]} WHERE MacAddress IN (SELECT MacAddress FROM ${sql_func[NBTSCAN_TEMP_TABLE_NAME]});"
-    
     # SQL to Import into final table for sorting
     sql_func[IMPORT_ARPSCAN_TEMP]="INSERT INTO ${sql_func[TEMP_TABLE_NAME]} (IpAddress,Hostname,MacAddress) SELECT IpAddress,Hostname,MacAddress FROM ${sql_func[ARPSCAN_TEMP_TABLE_NAME]};"
     sql_func[IMPORT_NBTSCAN_TEMP]="INSERT INTO ${sql_func[TEMP_TABLE_NAME]} (IpAddress,Hostname,MacAddress) SELECT IpAddress,Hostname,MacAddress FROM ${sql_func[NBTSCAN_TEMP_TABLE_NAME]};"
-    
-    
     # SQL for importing values
     sql_func[IMPORT_DISTINCT_SCAN_DATA]="INSERT INTO ${sql_func[TABLE_NAME]} (IpAddress,Hostname,MacAddress) SELECT DISTINCT IpAddress,Hostname,MacAddress FROM ${sql_func[TEMP_TABLE_NAME]} WHERE MacAddress NOT IN (SELECT DISTINCT MacAddress FROM ${sql_func[TABLE_NAME]});"
-    
     # SQL for showing unique values
     sql_func[SHOW_DISTINCT_SCAN_DATA]="SELECT DISTINCT IpAddress,Hostname,MacAddress FROM ${sql_func[TEMP_TABLE_NAME]} WHERE MacAddress NOT IN (SELECT DISTINCT MacAddress FROM ${sql_func[TABLE_NAME]});"
-    
     # SQL for Dropping Tables
     sql_func[DROP_TEMP_TABLE]="DROP TABLE IF EXISTS ${sql_func[TEMP_TABLE_NAME]};"
     sql_func[DROP_TEMP_ARPSCAN_TABLE]="DROP TABLE IF EXISTS ${sql_func[ARPSCAN_TEMP_TABLE_NAME]};"
     sql_func[DROP_TEMP_NBTSCAN_TABLE]="DROP TABLE IF EXISTS ${sql_func[NBTSCAN_TEMP_TABLE_NAME]};"
-    
     # SQL for Querying
     sql_func[SHOW_ALL]="SELECT * FROM ${sql_func[TABLE_NAME]};"
     sql_func[SEARCH_DB_SIMILAR]="SELECT Hostname,IpAddress,MacAddress FROM ${sql_func[TABLE_NAME]} WHERE Hostname LIKE '$STRING%';"
@@ -122,6 +105,13 @@ create_temp_tables()
     $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql CREATE_TEMP_TABLE)"
     $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql CREATE_ARPSCAN_TEMP_TABLE)"
     $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql CREATE_NBTSCAN_TEMP_TABLE)"
+}
+
+drop_temp_tables()
+{
+    $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql DROP_TEMP_TABLE)"
+    $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql DROP_TEMP_ARPSCAN_TABLE)" 
+    $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql DROP_TEMP_NBTSCAN_TABLE)"
 }
 
 drop_duplicates_import()
@@ -149,36 +139,6 @@ scanner_arpscan()
     >> $TEMP_FILE
     echo -e '.separator ,'"\n"'.import' "$TEMP_FILE" $(load_sql ARPSCAN_TEMP_TABLE_NAME)\
     | $(load_sql DB_TYPE) $(load_sql DB_NAME)
-    clean_up
-}
-
-scanner_nmap() # This takes a while. I dont think it will survive the cut
-{
-    make_tmp
-    $SUDO $NMAP $LAN >> $TEMP_FILE
-    if [ $? -eq 0 ]; then
-        declare -a nmap_array=($(
-        grep -e report -e MAC "$TEMP_FILE" | \
-        sed -e '{
-            s/Nmap scan report for //g
-            s/MAC Address: //g
-            s/ (.\+//g
-        }'
-     ))    
-        clean_up
-        
-        make_tmp
-        nmap_array_len=${#nmap_array[@]}
-        echo -n > "$TEMP_FILE"
-        for (( i = 0; i <= $nmap_array_len; i++ )); do
-            while (( $(echo ${nmap_array[$i]} | grep -c '[0-9A-F]\+:') < 1 )); do
-                (( i++ ))
-            done
-            echo ${nmap_array[(( $i - 1 ))]}',NMAP-SCAN,'${nmap_array[$i]}
-            (( i++ ))
-        done
-    fi
-    less $TEMP_FILE
     clean_up
 }
 
@@ -219,19 +179,14 @@ config_load()
     echo -e "$HEADER_ENABLE\n$TABLE_MODE\n$TABLE_WIDTH"
 }
 
-import_load()
+do_scan_import()
 {
-    echo -e '.separator ,'"\n"'.import' "$TEMP_FILE" $(load_sql SCANNED_TABLE_NAME)
-}
-
-do_scan_import() # uses nbtscan (Best Option so far)
-{
-    config_settings
-    check_db # Starts first to see if db exists.
-    create_temp_tables
-        scanner_arpscan
-        scanner_nbtscan
-        drop_duplicates_import 
+    config_settings           # Sources the config file.
+    check_db                  # Starts first to see if db exists.
+    create_temp_tables        # Creates Temp tables.
+    scanner_arpscan
+    scanner_nbtscan
+    drop_duplicates_import 
     make_tmp
     # Sets Display settings, and show what will be imported.
     config_load >> $TEMP_FILE
@@ -240,11 +195,8 @@ do_scan_import() # uses nbtscan (Best Option so far)
     
     if [ $num -eq 0 ]; then
         echo -e "No records to import. Everything is up to date."
-        $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql DROP_TEMP_TABLE)"
-        $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql DROP_TEMP_ARPSCAN_TABLE)" 
-        $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql DROP_TEMP_NBTSCAN_TABLE)"
-        clean_up
-        exit 0
+        drop_temp_tables
+        graceful_exit
     else
         echo -e "Displaying $num records to be imported.\n"
         $(load_sql DB_TYPE) $(load_sql DB_NAME) < $TEMP_FILE
@@ -252,26 +204,16 @@ do_scan_import() # uses nbtscan (Best Option so far)
         read selection
         case $selection in
             [yY] )  $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql IMPORT_DISTINCT_SCAN_DATA)"
-                    $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql DROP_TEMP_TABLE)"
-                    $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql DROP_TEMP_ARPSCAN_TABLE)" 
-                    $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql DROP_TEMP_NBTSCAN_TABLE)"
+                    drop_temp_tables
                     echo -e "Success!"
-                    clean_up
-                    exit 
+                    graceful_exit
                     ;;
-            [nN] )  $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql DROP_TEMP_TABLE)"
-                    $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql DROP_TEMP_ARPSCAN_TABLE)" 
-                    $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql DROP_TEMP_NBTSCAN_TABLE)"
-                    echo -e "Import Aborted"
-                    clean_up
-                    exit 
+            [nN] )  drop_temp_tables
+                    error_exit "Import aborted"
                     ;;
             *)	    echo "Invalid entry. Abort" # Fix this up a bit
-                    $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql DROP_TEMP_TABLE)"
-                    $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql DROP_TEMP_ARPSCAN_TABLE)" 
-                    $(load_sql DB_TYPE) $(load_sql DB_NAME) "$(load_sql DROP_TEMP_NBTSCAN_TABLE)"
-                    clean_up
-                    exit 
+                    drop_temp_tables
+                    error_exit "Invalid entry" 
                     ;; 
         esac
     fi
@@ -306,7 +248,7 @@ clean_up()
 
 error_exit()
 {
-    echo "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+    echo "$(program_info PROGNAME): ${1:-"Unknown Error"}" >&2
     clean_up
     exit 1
 }
@@ -373,11 +315,16 @@ do_wakeup_one()
     read selection
     local MAC_ADDR=$(load_sql SELECT_MAC_ADDR | $(load_sql DB_TYPE) $(load_sql DB_NAME))
     case $selection in
-        [yY] ) wakeonlan $MAC_ADDR  ;;
-        [nN] ) echo "Exiting" ; exit ;;
-        * )    echo "invalid entry" ; exit ;;
+        [yY] )  wakeonlan $MAC_ADDR 
+                graceful_exit
+                ;;
+        [nN] )  echo "Exiting" 
+                graceful_exit 
+                ;;
+        * )     echo "invalid entry" 
+                graceful_exit
+                ;;
     esac
-    clean_up
 }
 
 do_wakeup_all()
@@ -388,11 +335,14 @@ do_wakeup_all()
     read selection
     local MAC_ADDR=$(load_sql SELECT_ALL_MAC_ADDR | $(load_sql DB_TYPE) $(load_sql DB_NAME))
     case $selection in
-        [yY] ) wakeonlan $MAC_ADDR  ;;
-        [nN] ) exit ;;
-        * )    echo "invalid entry" ; exit ;;
+        [yY] )  wakeonlan $MAC_ADDR
+                graceful_exit
+                ;;
+        [nN] )  echo "Wakeup Aborted"
+                graceful_exit 
+                ;;
+        * )     error_exit "Invalid entry" ;;
     esac
-    clean_up
 }
 
 package_check() 
@@ -437,4 +387,4 @@ package_check()
         exit 32
     fi
 }
-show_db
+do_scan_import
